# Generated by Django 4.1 on 2022-09-08 14:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "file",
                    models.FileField(null=True, upload_to="videos/", verbose_name=""),
                ),
                ("description", models.TextField()),
                ("skillName", models.CharField(max_length=50)),
                ("view_count", models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Creator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=300)),
                ("profilepic", models.ImageField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "storing_prev_now_rated_value",
                    models.IntegerField(blank=True, default=1, null=True),
                ),
                ("avg_rating", models.IntegerField(blank=True, default=1, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "rated_number",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(5),
                            django.core.validators.MinValueValidator(1),
                        ],
                    ),
                ),
                (
                    "content_rating",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.content",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=50)),
                ("fatherName", models.CharField(max_length=50)),
                ("motherName", models.CharField(max_length=50)),
                ("skillName", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("profilepic", models.ImageField(upload_to="images/")),
                (
                    "profileCreator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.creator"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="content",
            name="contentCreator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.creator"
            ),
        ),
    ]
