# Generated by Django 4.1.1 on 2022-09-16 17:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(null=True, upload_to=api.models.save_video, verbose_name=''),
        ),
    ]
