# Generated by Django 4.1.1 on 2022-09-16 17:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(default=56, upload_to=api.models.save_video, verbose_name=''),
            preserve_default=False,
        ),
    ]
