# Generated by Django 4.1.2 on 2022-10-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_user_profilepic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profilepic",
            field=models.ImageField(default="profilepic.jpg", upload_to="images/"),
        ),
    ]
